### ISSUE TITLE
[suggestion de modification minime] changer l'icône de l'oeil pour afficher les détails sur les listes

### ISSUE THREAD

**Issue by clementin-bonneau-riera** [AntoninLoubiere/WebDiakoluo#49]
Idée de changement: actuellement le bouton qui sert à afficher plus de détails sur une liste est un œil, mais il peut porter à confusion car au début on pense qu'il sert à masquer un élément de la liste ou la colonne.

| icône actuelle | suggestions d'icône |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/79161093/135499050-c44162a7-6262-4c33-b336-57eefa97a9fd.png) | ![image](https://user-images.githubusercontent.com/79161093/135499161-db95836f-5661-4646-ba96-bd3f40e7f29d.png) ![image](https://user-images.githubusercontent.com/79161093/135499433-db3916f6-aa9e-4935-ab6e-69a01873c2ea.png) |

Il serait peut être préférable pour l’accessibilité de mettre une icône [plus dans ce style](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Ainfo%3A) ou [comme ça pour éditer](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aedit%3A) ?

**Comment by AntoninLoubiere** [comment]
Merci pour ce report ! 
Normalement, le bouton éditer y est déjà, mais je vais modifier l'icon pour afficher les détails. Cela semble plus logique avec celui ci.
